name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx prettier --check .

  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.env

  test-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.env
          export-variables: true
      - run: |
          if [ "$fixtures_1" != "123" ]; then
            echo "Variables not exported"
            exit 1
          fi

  # test environment variables are prefixed
  test-export-prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.env
          export-variables: true
          export-variables-prefix: "TFVARS_"
      - run: |
          if [ "$TFVARS_fixtures_1" != "123" ]; then
            echo "Variables not exported"
            exit 1
          fi

  test-keys-lowercase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.case.env
          log-variables: true
          export-variables: true
      - run: |
          if [ -z "$fixtures_6" ]; then
            echo "Variable not set"
            exit 1
          fi
          echo "lower: $fixtures_6"
          echo "upper: $FIXTURES_6"
          echo "bypass: $Fixtures_6"

  test-keys-uppercase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.case.env
          log-variables: true
          export-variables: true
          keys-case: upper
      - run: |
          if [ -z "$FIXTURES_6" ]; then
            echo "Variable not set"
            exit 1
          fi
          echo "lower: $fixtures_6"
          echo "upper: $FIXTURES_6"
          echo "bypass: $Fixtures_6"

  test-keys-bypasscase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.case.env
          log-variables: true
          export-variables: true
          keys-case: bypass
      - run: |
          if [ -z "$Fixtures_6" ]; then
            echo "Variable not set"
            exit 1
          fi
          echo "lower: $fixtures_6"
          echo "upper: $FIXTURES_6"
          echo "bypass: $Fixtures_6"

  test-remove-node-options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./fixtures/.node_options.env
          log-variables: true
          export-variables: true
      - run: |
          env > env_output.txt
          cat env_output.txt
          if grep -q "Can't store NODE_OPTIONS output parameter using '\$GITHUB_ENV' command." env_output.txt; then
            echo "Warning: NODE_OPTIONS was removed by GitHub Actions."
            exit 1
          else
            echo "NODE_OPTIONS removed from environment."            
          fi
